export class CreateCarDto {
  name: string;
  brandId: string;
  model: string;
  year: number;
  rentalType: string;
  pricePerDay: number;
  priceTiers?: { days: number; pricePerDay: number; discountPercentage?: number }[];
  images: string[];
  description?: string;
  content?: string;
  location?: {
    country: string;
    state: string;
    city: string;
    address: string;
    latitude?: number;
    longitude?: number;
  };
  vehicleType?: string;
  transmission?: string;
  fuelType?: string;
  licensePlate?: string;
  vin?: string;
  mileage?: number;
  horsepower?: number;
  seats?: number;
  doors?: number;
  driveType?: string;
  cylinders?: number;
  insuranceInfo?: string;
  isUsed?: boolean;
  tags?: string[];
  amenities?: string[];
  colors?: string[];
   distanceIncluded?: number;
   extraDistanceFee?: number;
   extras?: {
      name: string;
      description?: string;
      price: number;
      priceType: 'per_day' | 'per_trip';
      category?: string;
   }[];
  documents?: { name: string; url: string; type: string; expiryDate?: Date }[];
  condition?: string;
  color?: string;
  acceleration?: number;
  chargingType?: string;
  batteryCapacity?: number;
  range?: number;
  pickupLocations?: {
    name: string;
    address: string;
    latitude?: number;
    longitude?: number;
    price: number;
  }[];
  customSpecs?: Record<string, any>;
}
